export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_DATA_SUCCESS = "PURCHASE_DATA_SUCCESS";
export const PURCHASE_DATA_FAIL = "PURCHASE_DATA_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDER_INIT = "FETCH_ORDER_INIT";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_INIT_AUTO = "AUTH_USER_INIT_AUTO";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
